version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  report:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run report
      - run:
          command: npx hardhat test
workflows:
  test&coverage_report:
    jobs:
      - report
